CREATE DATABASE `app`;

USE `app`;

CREATE TABLE `User` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(50) NOT NULL,
  `Limit` INT(10),
  `Version` INT(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `Name_Unique` (`Name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Authorities` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `UserID` INT(10) NOT NULL,
  `Authority` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `Auth_UniqueKey` (`UserID`, `Authority`),
  CONSTRAINT `FK_Auth_User` FOREIGN KEY (`UserID`) REFERENCES `User` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Record` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `UserID` INT(10) NOT NULL,
  `Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Description` VARCHAR(255) NOT NULL,
  `Value` INT(10) NOT NULL,
  `Version` INT(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_Rec_User` FOREIGN KEY (`UserID`) REFERENCES `User` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
